=== abnotePia/llenguatgeDeMarques/EXAMEN/XML+Validacio/comprovar.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="grups">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="grup"  minOccurs="1" maxOccurs= "unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nom">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="5"/>
										<xs:maxLength value="60"/>
									</xs:restriction>
							</xs:simpleType>
							</xs:element>
							<xs:element name="alumnes">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="alumne" minOccurs="1" maxOccurs= "unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="nom" type="xs:string"/>
													<xs:element name="cognoms" type="xs:string"/>
													<xs:element name="edat">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:minInclusive value="15"/>
																</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="confinament">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="motiu">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:pattern value="Positiu|Contacte"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="Data_inici_confinament"/>
																<xs:element name="Dies_confinament" type="xs:integer" default="10"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
											</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="codi">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="[A-Z]{3}[0-9]{1}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== abnotePia/llenguatgeDeMarques/EXAMEN/XML+Validacio/exercici1.xml
<?xml version="1.0" encoding="utf-8"?>
<grups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="comprovar.xsd">
	<grup codi="DAM1">
		<nom>1er Desenvolupament d'aplicacions multiplataforma</nom>
		<alumnes>
			<alumne>
				<nom>Alberto</nom>
				<cognoms>Bueno Miera</cognoms>
				<edat>22</edat>
				<confinament>
					<motiu>Positiu</motiu>
					<Data_inici_confinament>19/09/2020</Data_inici_confinament>
					<Dies_confinament>14</Dies_confinament>
				</confinament>
			</alumne>
			<alumne>
				<nom>Miguel Angel</nom>
				<cognoms>Turdo Senarriaga</cognoms>
				<edat>24</edat>
				<confinament>
					<motiu>Contacte</motiu>
					<Data_inici_confinament>20/10/2020</Data_inici_confinament>
					<Dies_confinament>10</Dies_confinament>
				</confinament>
			</alumne>
		</alumnes>
	</grup>
	<grup codi="SMX1">
		<nom>1er Sistemes microinformàtics i xarxes</nom>
		<alumnes>
			<alumne>
				<nom>Jesus</nom>
				<cognoms>Jimenez Zorriqueta</cognoms>
				<edat>15</edat>
				<confinament>
					<motiu>Contacte</motiu>
					<Data_inici_confinament>12/09/2020</Data_inici_confinament>
					<Dies_confinament>14</Dies_confinament>
				</confinament>
			</alumne>
			<alumne>
				<nom>Vanesa</nom>
				<cognoms>Perrote Varela</cognoms>
				<edat>16</edat>
				<confinament>
					<motiu>Contacte</motiu>
					<Data_inici_confinament>24/09/2020</Data_inici_confinament>
					<Dies_confinament>10</Dies_confinament>
				</confinament>
			</alumne>
		</alumnes>
	</grup>
	<grup codi="SMX2">
		<nom>2on Sistemes microinformàtics i xarxes</nom>
		<alumnes>
			<alumne>
				<nom>Vicente</nom>
				<cognoms>Lafuente Tevenet</cognoms>
				<edat>16</edat>
				<confinament>
					<motiu>Positiu</motiu>
					<Data_inici_confinament>18/09/2020</Data_inici_confinament>
					<Dies_confinament>14</Dies_confinament>
				</confinament>
			</alumne>
		</alumnes>
	</grup>
</grups>
